### PR TITLE
Windowedfullscreen fix

### LINKED ISSUE #5228: Bug on trying to change display settings to windowed fullscreen
### General Info

Terasology Launcher Version: 4.8.0
Terasology Version: 5.3.0
Operating System: Windows 10 x64
Onboard / Dedicated Graphics: Nvidia gtx 1650ti
Java Version: Version 8 361

### What you were trying to do

I was attempting to change the display settings to windowed fullscreen to be able to easily switch windows etc..

### What actually happened

The screen was still showing the taskbar

### How to reproduce

1. Select Terasology version '5.3.0'
1. Start Terasology
1. Go to settings then video settings
1. Change the display mode to windowed fullscreen

### Log details

No crash

### Screenshots

here's a link to a video recording showing the process

https://drive.google.com/file/d/1-eZ1HBAPBV6kSBvPoEG-LBjZGtJhWacp/view?usp=sharing

### PR DESCRIPTION
**Pull request by Khaled-Dridi**
this PR fixes #5228 when windowed full screen is pressed it will still show the task bar i fix that buy making it double click the windowed full screen so it will change its state twice (i used for loop for that)

How to test
go to setting go to video change to windowed then change to windowed full screen
because previously when you press windowed then press windowed fullscreen it will keep the task bar

Outstanding before merging
If anything. You can use neat checkboxes! Feel free to delete if not needed

[no ] Need to consider use case x
[no ] Still have to adjust the wiki doc
[no ] Will need translation work

### CODE REVIEW

File: engine/src/main/java/org/terasology/engine/core/subsystem/lwjgl/LwjglDisplayDevice.java [hunk 1]
```diff
@@ -78,6 +78,7 @@ public void setDisplayModeSetting(DisplayModeSetting displayModeSetting) {
         setDisplayModeSetting(displayModeSetting, true);
     }
 
+    @SuppressWarnings({"checkstyle:WhitespaceAround", "checkstyle:WhitespaceAfter"})
```
Comment (BenjaminAmos) [inline engine/src/main/java/org/terasology/engine/core/subsystem/lwjgl/LwjglDisplayDevice.java]:
```suggestion
```
You should not be introducing any new checkstyle warnings in new code. Suppressions are for exceptional cases only.

File: engine/src/main/java/org/terasology/engine/core/subsystem/lwjgl/LwjglDisplayDevice.java [hunk 2]
```diff
@@ -88,13 +89,15 @@ public void setDisplayModeSetting(DisplayModeSetting displayModeSetting, boolean
...
-                        GLFW.GLFW_DONT_CARE);
+                for(int i=0;i<2;i++){
+                    GLFW.glfwSetWindowMonitor(window,
+                            MemoryUtil.NULL,
+                            0,
+                            0,
+                            vidMode.width(),
+                            vidMode.height(),
+                            GLFW.GLFW_DONT_CARE);
+                }
```
Comment (BenjaminAmos) [inline engine/src/main/java/org/terasology/engine/core/subsystem/lwjgl/LwjglDisplayDevice.java]:
```suggestion
                // Attempt to go into fullscreen twice to fix the taskbar showing on-top of the game on Windows.
                // See also: https://github.com/MovingBlocks/Terasology/issues/5228.
                for (int i = 0; i < 2; i++) {
                    GLFW.glfwSetWindowMonitor(window,
                            MemoryUtil.NULL,
                            0,
                            0,
                            vidMode.width(),
                            vidMode.height(),
                            GLFW.GLFW_DONT_CARE);
                }
```

Given that this is a very unusual solution, I think it deserves a comment to explain why it is done this way. The suggestions above should also fix the checkstyle issues.

**Review by BenjaminAmos — COMMENTED** [review]
Thanks for fixing this! The changes here are mostly fine but I cannot accept supressing checkstyle warnings for no good reason. Please try and fix those first.

For future reference, you do not need to open a new pull request every time you make changes. You can just push new commits to this pull request's branch and they will been shown here.

**Comment by Khaled-Dridi** [comment]
> Thanks for fixing this! The changes here are mostly fine but I cannot accept supressing checkstyle warnings for no good reason. Please try and fix those first.
> 
> For future reference, you do not need to open a new pull request every time you make changes. You can just push new commits to this pull request's branch and they will been shown here.

can you rereview it I did what you told me to do  and ty

**Comment by BenjaminAmos** [comment]
I was all ready to approve this earlier but after testing it again it does not appear to work anymore? I was looking through the changes and it is puzzling. Did you test this version before submitting it?

The only difference I can see from your last pull request is that the following line is not run twice anymore. Could that be related?
https://github.com/MovingBlocks/Terasology/blob/072d20742eff71bc2f34f358af399b59ae2d375c/engine/src/main/java/org/terasology/engine/core/subsystem/lwjgl/LwjglDisplayDevice.java#L98

**Comment by Khaled-Dridi** [comment]
> I was all ready to approve this earlier but after testing it again it does not appear to work anymore? I was looking through the changes and it is puzzling. Did you test this version before submitting it?
> 
> The only difference I can see from your last pull request is that the following line is not run twice anymore. Could that be related?
> 
> https://github.com/MovingBlocks/Terasology/blob/072d20742eff71bc2f34f358af399b59ae2d375c/engine/src/main/java/org/terasology/engine/core/subsystem/lwjgl/LwjglDisplayDevice.java#L98

yes i did test it and it worked for me i will check it again when i am next to my laptop

**Comment by Khaled-Dridi** [comment]
@BenjaminAmos  hi there i found the problem and i posted a new commit if you can check it that would be great

**Review by BenjaminAmos — APPROVED** [review]
