### PR TITLE
Fixed #1764, possibly fixed #1767 (needs to be looked up) and some other improvements

### LINKED ISSUE #1764: Prefabs and entities with Collection (List/Set) of @ManagedContainer type objects are not read correctly
Entities with component that has a collection of @ManagedContainer objects throw exception when getting deserialized (with old asset code, did not check new one).

Also, prefabs with such configuration cannot be loaded (throw an exception).

### LINKED ISSUE #1767: PreBegin method is called after world is loaded, contrary to what JavaDoc says
PreBegin method of ComponentSystem is called after world is loaded, which is the opposite of what the javadoc for that method says.

### PR DESCRIPTION
**Pull request by MarcinSc**
The other improvements are:
- reduced the number of Rotations (to only those possible),
- removed AllSidesBlockFamily - doesn't make sense, as the "top" and "bottom" one does not have well defined sides,
- added method "getSide(Block)" to SideDefinedBlockFamily to avoid calling "Block::getDirection()" that will most likely be removed.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/135/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
I figure this is the second coming of #1735 now that the big merge is done, right? And will probably be what helps fix the few broken modules likely set up to take advantage of this.

In any case it has architecture written all over it so casting Summon @immortius for review :-)

@emanuele3d was interested last go-around too so ping!

File: engine/src/main/java/org/terasology/math/Rotation.java [hunk 1]
```diff
@@ -79,19 +82,40 @@ public static Rotation rotate(Yaw yaw, Pitch pitch, Roll roll) {
         return ROTATIONS.get(indexFor(yaw, pitch, roll));
     }
 
+    public static Rotation findReverse(Rotation rotation) {
+        Side frontResult = rotation.rotate(Side.FRONT);
```
Comment (immortius) [inline engine/src/main/java/org/terasology/math/Rotation.java]: I would suggest the reverse of a rotation should be the rotation that undoes the rotation. I'm not sure this code achieves this? If it does I think there is a likely a more direct way of achieving it.

I also assume that null shouldn't be a legitimate result, I would suggest a RuntimeException thrown instead.

File: engine/src/main/java/org/terasology/math/Rotation.java [hunk 2]
```diff
@@ -17,24 +17,27 @@
...
  * <br><br>
  * Uses the fly weight pattern to cache the 64 combinations of rotation.
+ * Note (Marcin Sciesinski): there are actually only 24 possible combinations, the remaining 40 are just duplicates
  *
  * @author Immortius
  */
 public final class Rotation {
 
     private static final TByteObjectMap<Rotation> ROTATIONS;
+    private static final TByteByteMap DUPLICATE_ROTATIONS;
```
Comment (immortius) [inline engine/src/main/java/org/terasology/math/Rotation.java]: Is this needed? Why not just put the same rotation into multiple positions of the main map?

File: engine/src/main/java/org/terasology/math/Rotation.java [hunk 3]
```diff
@@ -17,24 +17,27 @@
...
 
 import java.util.List;
 
-import org.terasology.math.geom.Quat4f;
-
 /**
  * Rotation provides easy access to 90 degree increments of rotations - intended for block-related rotations.
  * <br><br>
  * Uses the fly weight pattern to cache the 64 combinations of rotation.
+ * Note (Marcin Sciesinski): there are actually only 24 possible combinations, the remaining 40 are just duplicates
```
Comment (immortius) [inline engine/src/main/java/org/terasology/math/Rotation.java]: This assumes you don't care about the actual yaw/pitch/roll, only the resultant rotation. Is this a safe assumption? Yaw/pitch/roll are visible attributes.

File: engine/src/main/java/org/terasology/persistence/serializers/EntityDataJSONFormat.java [hunk 4]
```diff
@@ -364,8 +364,8 @@ public JsonElement serialize(EntityData.Value src, Type typeOfSrc, JsonSerializa
                 for (JsonElement element : jsonArray) {
                     if (element.isJsonArray()) {
                         value.addValue((EntityData.Value) context.deserialize(element, EntityData.Value.class));
-                    } else if (json.isJsonObject()) {
-                        extractMap(json, context, value);
+                    } else if (element.isJsonObject()) {
```
Comment (immortius) [inline engine/src/main/java/org/terasology/persistence/serializers/EntityDataJSONFormat.java]: Good catch

File: engine/src/main/java/org/terasology/math/Rotation.java (hunk 1 above)
Comment (immortius) [inline engine/src/main/java/org/terasology/math/Rotation.java]: Ok, I've had a closer look. This does achieve that result.

File: engine/src/main/java/org/terasology/math/Rotation.java [hunk 5]
```diff
@@ -17,24 +17,27 @@
...
  *
  * @author Immortius
  */
 public final class Rotation {
```
Comment (immortius) [inline engine/src/main/java/org/terasology/math/Rotation.java]: I'm going to suggest it would probably clean up the code to change this to calculate all the rotations up front - with each new rotation, checking to see if any of the previous rotations have the same value and using that existing rotation instead. Additionally, after all the rotations are created determining the opposite rotation for each one and setting that as a value in the rotations.

File: engine/src/main/java/org/terasology/persistence/typeHandling/protobuf/ProtobufPersistedData.java [hunk 6]
```diff
@@ -40,9 +40,11 @@
 import org.terasology.protobuf.EntityData;
 
 import java.nio.ByteBuffer;
+import java.util.HashMap;
```
Comment (immortius) [inline engine/src/main/java/org/terasology/persistence/typeHandling/protobuf/ProtobufPersistedData.java]: Seems to be a couple of unused imports here.

File: engine/src/main/java/org/terasology/math/Rotation.java (hunk 3 above)
Comment (immortius) [inline engine/src/main/java/org/terasology/math/Rotation.java]: I might even suggest keeping the 64 rotations, but providing a normalise method that provides the "base" rotation which has identical effect, if a person wants to work with just the 24 resultant rotations. ;)

File: engine/src/main/java/org/terasology/world/block/family/SideDefinedBlockFamily.java [hunk 7]
```diff
@@ -20,4 +20,5 @@
 
 public interface SideDefinedBlockFamily extends BlockFamily {
```
Comment (immortius) [inline engine/src/main/java/org/terasology/world/block/family/SideDefinedBlockFamily.java]: While not a matter for this PR, I don't feel this interface conveys its meaning very well. By side here we actually mean what, the facing direction of the block? Would this conveyed better if it was called SideFacingBlockFamily, and the methods be ```Block getBlockFacing(Side)``` and ```Side getFacingSideOf(Block)```

**Comment by immortius** [comment]
> Moved FullRotationFamily to Signalling, though I'm sure it will be copy/pasted to many mods.

This is an argument for it being in a common module, not being in engine. The point of engine is to provide the minimum required to support the game, not to provide features that of common or even universal appeal. I know there is a lot of cruft in engine, and we have not always done well at keeping to this principle, but I still feel we should aspire to it.

I suggest we should create a new "common" module, siphon anything relevant out of core into it, add your FullRotationFamily, and start maintaining this as a source for commonly useful but piecemeal features, at least until enough stuff builds up that it makes sense to split them out into separate modules.  Would need to come up with some inclusion guidelines along the lines of guava (need to ensure things are commonly useful and not just some neat feature which one person needs).

**Comment by immortius** [comment]
>Would this be a convenient time to also mark Block.getDirection() and Block.setDirection(...) as deprecated (or I suppose even remove it)? To me it seemed like this getSide(...) functionality was its intention.

@Josharias Maybe. Should we chuck get/setRotation into Block, and not bother with the getSide()?

**Comment by MarcinSc** [comment]
I'm ok with modifying the Block to have "get/setRotation" instead of "getSide", or just dropping the "getSide" all together.

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/TerasologyPRs/136/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
A related common misc module was made last time around :-)

https://github.com/Terasology/MarcinScIncubator

Until we find a more permanent home for utility stuff, anyway. Yeah we could do a more common(ly named) module instead, but no big difference for now.

**Comment by MarcinSc** [comment]
@Cervator That is in fact, where the FullRotationFamily (and associated classes) currently resides.

**Comment by Josharias** [comment]
I now agree with @MarcinSc about taking out Block.getDirection() in favor of the block family implementation of what direction a block is facing.  Using the block family is the only way that modules can attach extra metadata to a particular block (in this case, the facing direction) because the Block class is final.  The Block class should probably keep to the purpose of determining how a block is displayed in the world.

The other direction we could go is to allow subclasses of Block to be created and returned from the block family.  That would allow creation of a BlockThatFacesADirection class that would then contain the method that returns the direction.  However, I am unsure if that would cause all sorts of other problems in the rest of the engine.

**Comment by immortius** [comment]
Extra information can be attached to blocks via their prefabs as well - although this is awkward currently. Ideally blocks will ultimately just be entities or prefabs and the block class will disappear.

The block family is not an intended method of adding data, only to group blocks and provide the algorithms to decide which to use in different situations. Sides/rotations/directions tie into this.

**Comment by Cervator** [comment]
So is that a Yea or Nay on this PR's approach for now? Or more related to future architectural plans with this PR good to merge?

**Comment by immortius** [comment]
I am happy with the PR, yes. :)
