### PR TITLE
fix!(BlockRegion): Rewrite of BlockRegion

### LINKED ISSUE #4086: BlockRegion intersection tests incorrect.
All of the BlockRegion.intersects* methods with floating-point arguments and the BlockRegion.containsPoint(Vector3fc) method are incorrect. The actual position of the corner of a BlockRegio is not (region.aabb.minX, region.aabb.minY, region.aabb.minZ) but (region.aabb.minX-0.5, region.aabb.minY-0.5, region.aabb.minZ-0.5), as points in the world with integer coordinates are actually at the centres of the blocks with the corresponding integer coordinates, not the corner. This means that the region covered by the BlockRegion is not the same as the region covered by its AABB.

Currently none of these BlockRegion methods seem to be actually used, so this does not manifest as an actual bug. Ideally it shouldn't be left in this state though, and the methods should be either corrected or removed.

### PR DESCRIPTION
**Pull request by QuentinAndre11**
### Contains

Fixes #4086 
BlockRegion intersection tests were based on the center of the blocks instead of their corner, and we fixed it.

### How to test

We added unit tests, you can run it or add some tests if you think that some are missing. It's impossible to test it in the game because these functions seem to be currently unused. 

### Outstanding before merging

These methods might be removed because currently unused,

### CODE REVIEW

**Review by pollend — CHANGES_REQUESTED** [review]
I think it would be ideal to drop the AABBi object and replace it with an AABBf to just cache the floating point position. replace AABBi with 6 integer values for the min and max. for getMax you don't need to +1 and -1 for that calculation anymore since AABBi doesn't represent the bounds of the region anymore.  we also want to avoid declaring temporary objects in this way to avoid unnecessary GC. 

image

File: engine/src/main/java/org/terasology/world/block/BlockRegion.java [hunk 1]
```diff
@@ -25,20 +25,39 @@
...
+    /**
+     * The y coordinate of the maximum corner.
+     */
+    public int maxY = Integer.MIN_VALUE;
     /**
-     * AABB region that backs a BlockRegion
+     * The z coordinate of the maximum corner.
      */
-    public final AABBi aabb = new AABBi();
+    public int maxZ = Integer.MIN_VALUE;
```
Comment (skaldarnar) [inline engine/src/main/java/org/terasology/world/block/BlockRegion.java]: @pollend Should those really be public? I'm a bit confused right now, as I thought we agreed on Slack with @4Denthusiast that we should ensure that invalid min/max combinations should throw exceptions. With these values publicly accessible we cannot guarantee that...

File: engine/src/main/java/org/terasology/world/block/BlockRegion.java [hunk 2]
```diff
@@ -792,36 +1026,50 @@ public BlockRegion addExtents(int extentX, int extentY, int extentZ, BlockRegion
...
+
+        dest.maxX = Math.roundUsing(this.maxX + extentX, RoundingMode.CEILING);
+        dest.maxY = Math.roundUsing(this.maxY + extentY, RoundingMode.CEILING);
+        dest.maxZ = Math.roundUsing(this.maxZ + extentZ, RoundingMode.CEILING);
 
-        dest.aabb.maxX = Math.roundUsing(this.aabb.maxX + extentX, RoundingMode.CEILING);
-        dest.aabb.maxY = Math.roundUsing(this.aabb.maxY + extentY, RoundingMode.CEILING);
-        dest.aabb.maxZ = Math.roundUsing(this.aabb.maxZ + extentZ, RoundingMode.CEILING);
         return dest;
     }
```
Comment (pollend) [inline engine/src/main/java/org/terasology/world/block/BlockRegion.java:1039]: I'm pretty sure this logic is incorrect @4Denthusiast

File: engine/src/main/java/org/terasology/world/block/BlockRegion.java [hunk 3]
```diff
@@ -297,24 +287,20 @@ public BlockRegion set(BlockRegion source) {
...
-        }
-        return bounds;
+    public AABBf getBounds(AABBf dest) {
+        dest.minX = minX - .5f;
+        dest.minY = minY - .5f;
+        dest.minZ = minZ - .5f;
+
+        dest.maxX = minX + .5f;
+        dest.maxY = minY + .5f;
+        dest.maxZ = minZ + .5f;
```
Comment (4Denthusiast) [inline engine/src/main/java/org/terasology/world/block/BlockRegion.java:301]: maxZ, not minZ (and similarly for the other two).

File: engine/src/main/java/org/terasology/world/block/BlockRegion.java (hunk 2 above)
Comment (skaldarnar) [reply engine/src/main/java/org/terasology/world/block/BlockRegion.java:1039]: Agreed (and I've added a test for that). But I'm also not sure whether there's a value in this method anymore, now that we treat integer coordinates as block centers. I think the following should hold (and could be the implementation):

```java
public BlockRegion addExtents(float extentX, float extentY, float extentZ, BlockRegion dest) {
	return addExtents(Math.roundUsing(extentX, RoundingMode.FLOOR), 
		Math.roundUsing(extentY, RoundingMode.FLOOR), 
		Math.roundUsing(extentZ, RoundingMode.FLOOR), dest);
}
```

**Comment by skaldarnar** [comment]
@QuentinAndre11 Sorry for "hijacking" this PR 😅 Your initial PR was right on point - highly appreciated! We just realized there is a lot more work needed to get this right 🙈 So, we just took the liberty to add more and more commits ourselves...

Please feel free to participate in this coding party. At this point, more tests are appreciated, as well as careful review of all the changes here.

**Review by pollend — APPROVED** [review]

File: engine/src/main/java/org/terasology/world/block/regions/BlockRegionComponent.java [hunk 4]
```diff
@@ -8,15 +8,19 @@
...
 /**
+ *
  */
 public class BlockRegionComponent implements Component {
+    /**
+     * May be null.
+     */
     @Replicate
-    public BlockRegion region = new BlockRegion();
+    public BlockRegion region;
```
Comment (skaldarnar) [inline engine/src/main/java/org/terasology/world/block/regions/BlockRegionComponent.java:18]: I think this will have some implications, as it could not be null before.

I haven't double-checked where this component is used/accessed.

Comment (pollend) [reply engine/src/main/java/org/terasology/world/block/regions/BlockRegionComponent.java:18]: hmm, so an empty blockmap is null.

File: engine/src/main/java/org/terasology/world/block/BlockRegions.java [hunk 5]
```diff
@@ -53,7 +56,7 @@ public static BlockRegion createFromMinAndMax(int minX, int minY, int minZ, int
      * @return new block region
      */
     public static BlockRegion createFromCenterAndExtents(Vector3ic center, Vector3ic extents) {
-        return new BlockRegion().union(center).addExtents(extents);
+        return new BlockRegion(center).extend(extents);
```
Comment (skaldarnar) [inline engine/src/main/java/org/terasology/world/block/BlockRegions.java:59]: I'm not sure this is intuitive - while writing tests for this, I was wondering whether 
```java
BlockRegions.createFromCenterAndExtents(new Vector3i(), new Vector3i(0,0,0))
```
is valid or not, and what it should return. In the given implementation it _is valid_, as the extents are added to the center block, while the utility method might be interpreted in a way that "extents" refers to the final extents...

File: engine/src/main/java/org/terasology/world/block/BlockRegion.java [hunk 6]
```diff
@@ -19,317 +19,384 @@
...
 
-    public BlockRegion(BlockRegion source) {
-        aabb.set(source.aabb);
+    /**
+     * Creates an empty block region with invalid minimum/maximum corners.
+     * <p>
+     * {@link #isValid()} will return {@code false} for an empty block region created via this constructor.
+     */
+    @Deprecated
+    BlockRegion() {
```
Comment (skaldarnar) [inline engine/src/main/java/org/terasology/world/block/BlockRegion.java:62]: This is not public anymore, so there is hopefully no way to create invalid BlockRegions anymore. However, this comes in very handy when redcuing a list of positions in the `encompassing` helper methods, that's why I left it in...

Not sure what to do with it...

Comment (pollend) [reply engine/src/main/java/org/terasology/world/block/BlockRegion.java:62]: I wouldn't mark it as deprecated though.
