### PR TITLE
Fix multi unbinding problem

### LINKED ISSUE #2831: Can't unbind multiple keys
### What you were trying to do

Unbind multiple keys in one game session.

The first unbind works, but subsequent ones don't.

### What actually happened

The dialog box hangs (the "ok" button stays pressed down, but the dialog box stays open and doesn't do anything. It can be closed, but the button will not be unbound).

### How to reproduce

* Open up settings->input
* Click on a key to unbind
* Click remove
* Click OK
* This first one should unbind successfully
* Repeat the process
* The second and subsequent unbinds will not work
* Pressing "Restore Defaults" or restarting the game will allow you to unbind one more, but will break again on subsequent unbinds

### Log details and game version
Game version: tested both on the latest source tree (commit 7e3ba2c), and the Omega 691 binaries from http://forum.terasology.org/threads/play-test-session-sunday-march-19th-1-pm-us-eastern-time.1814/.

Relevant log:

18:33:51.967 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event java.lang.NullPointerException: null
        at org.terasology.rendering.nui.layers.mainMenu.inputSettings.ChangeBindingPopup.lambda$initialise$232(ChangeBindingPopup.java:70)
        at org.terasology.rendering.nui.widgets.UIButton.activate(UIButton.java:203)
        at org.terasology.rendering.nui.widgets.UIButton.access$100(UIButton.java:41)
        at org.terasology.rendering.nui.widgets.UIButton$1.onMouseRelease(UIButton.java:99)
        at org.terasology.rendering.nui.internal.CanvasImpl.processMouseRelease(CanvasImpl.java:247)
        at org.terasology.rendering.nui.internal.NUIManagerInternal.mouseButtonEvent(NUIManagerInternal.java:577)
        at org.terasology.rendering.nui.internal.NUIManagerInternalMethodAccess.invoke(Unknown Source)
        at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
        at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:279)
        at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:258)
        at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
        at org.terasology.input.InputSystem.sendMouseEvent(InputSystem.java:545)
        at org.terasology.input.InputSystem.processMouseInput(InputSystem.java:332)
        at org.terasology.input.InputSystem.update(InputSystem.java:279)
        at org.terasology.engine.modes.StateIngame.handleInput(StateIngame.java:179)
        at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:54)
        at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:422)
        at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:368)
        at org.terasology.engine.Terasology.main(Terasology.java:152)

### Computer details
GNU/Linux Ubuntu 16.10

### PR DESCRIPTION
**Pull request by ThompsonTyler**
### Contains

Fixes #2831 

There was a problem with checking if a bind input was bound and two inputs are both null, 
Could be solved a few different ways, but I figured the most plausible would be that no matter what null is never registered as bound to other inputs(even if it technically is).

### How to test

Unbind 1 key, try unbinding a second(and a third and a fourth if you don't trust it) and it will now allow you to unbind these keys. 

Test in game that they are properly unbound and then rebind and see that they still work when rebound(the fix doesn't break the input binding system)

### Outstanding before merging

Double check that this is how we want to deal with unbinding keys and setting their input values to null.

There are a few different ways this could be done, this is just one of them.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

File: engine/src/main/java/org/terasology/config/BindsConfig.java [hunk 1]
```diff
@@ -82,7 +82,7 @@ public BindsConfig() {
      * @return True if newInput has been bound. False otherwise.
      */
     public boolean isBound(Input newInput) {
-        return data.containsValue(newInput);
+        return data.containsValue(newInput) && newInput != null;
```
Comment (vampcat) [inline engine/src/main/java/org/terasology/config/BindsConfig.java]: This is a minor nitpick, but a "newInput != null; && data.containsValue(newInput)" will be much more efficient when newInput is null, because of the most programming languages handle AND (using short circuit logic).

Comment (ThompsonTyler) [inline engine/src/main/java/org/terasology/config/BindsConfig.java]: Good point, completely missed that optimization. Will fix real quick.
