### PR TITLE
Quick fix for the visual artifact caused by DirectionalLightsNode

### LINKED ISSUE #2392: Rendering freaks out when maximizing the game windows
### What you were trying to do
Switching to maximized window

### What actually happened
Rendering freaks out completely, like this:
https://www.dropbox.com/s/eavi910v0e0kj80/bug2.PNG?dl=0

Switching back to normal window size doesn't fix the problem.

### How to reproduce

* Open Terasology on Windows
* Enter a world
* Maximize the game window

### Log details and game version
The log doesn't output any errors, everythings normal there
Version: latest build, also happens in dev environment

### Computer details
Windows 10, 64-bit, NVidia GeForce GTX 850M

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/35704721-rendering-freaks-out-when-maximizing-the-game-windows?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by tdgunes**
### Contains

out

As title says, quick fix for the bug which was introduced in c301a69f4676f4a469c56ee126f0ff9966624b30. 

Probably fixes #2392.

### How to test

Load the game and try to resize the window.

_Side note: Sorry for this tiny bug, human errors 😞  Hopefully not caused any fatalities, hoping it was just a little frustration to fellow gamers._

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
I feel relatively confident in saying no gelatinous cubes were harmed during the creation or resolution of this bug :D

Can also confirm the fix as I can provoke the issue via resizing the window (but oddly not by going to fullscreen, like I tested over in #2392)

Thanks!

File: engine/src/main/java/org/terasology/rendering/dag/DirectionalLightsNode.java [hunk 1]
```diff
@@ -83,6 +82,7 @@ private void initMainDirectionalLight() {
     @Override
     public void process() {
         PerformanceMonitor.startActivity("rendering/directionallights");
+        sceneOpaque = frameBuffersManager.getFBO("sceneOpaque");
```
Comment (emanuele3d) [inline engine/src/main/java/org/terasology/rendering/dag/DirectionalLightsNode.java]: Good catch!!!
