### PR TITLE
Fix crash when system locale is complex

### LINKED ISSUE #5157: Building from source won't work with "complex" system locales
### What you were trying to do

Build from source!

### What actually happened

On one of my machines the system locale is a two-parter, `en_UA` (English language, Ukrainian region). Unfortunately, Java expects a two-letter locale (just the language). So this leads to a cascade of errors:
```
14:21:56.939 [main] WARN  o.t.e.c.f.c.LocaleConstraint - Locale en_UA should be one of [,nn,ar,bg,kea,nds,zu,am,fr,ti,bo, ... many other 2 letter codes ...]
```
```
14:21:56.942 [main] ERROR o.t.g.u.r.SimpleClassFactory - Failed to instantiate class: class org.terasology.engine.config.SystemConfig
...
Caused by: java.lang.IllegalArgumentException: The default value must be a valid value. Check the logs for more information.
```
```
14:21:57.024 [main] ERROR o.t.engine.core.TerasologyEngine - Failed to initialise Terasology
java.lang.NullPointerException: null
```

### How to reproduce

Build from source on a similar machine. I'll have a fix for this soon though!

### PR DESCRIPTION
**Pull request by rzats**
### Contains

Fixes #5157. Detects if a locale looks like e.g. `en_UA` and converts it to e.g. `en`, preventing a game crash.

Also re-enables the *ancient* part-pirate localization by adding it to the "whitelist" of allowed locales.

### How to test

Build from source with a "weird locale" (I did this on a non-M1/M2 Mac) and verify the game no longer crashes :)

### CODE REVIEW

**Review by jdrueckert — DISMISSED** [review]

**Review by soloturn — CHANGES_REQUESTED** [review]
i do think mixing language and region is the wrong approach. @rzats to my knowledge en_UA would mean that ukraine has a different english variant, so with maybe different words, grammar, etc. that variant of english seems to be not standardized, as @jdrueckert remarks. setting en_IE, en_US, en_UK, en_CA works. the region you live in is set in different variables, here an example from romania, some english variant is set, as it is perfectly fine to use american english in romania, while the other LC_ variables are set to region romania:
https://www.baeldung.com/linux/locale-environment-variables

what does ```public static Locale.Category[] values()``` return for you?

see:
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Locale.Category.html

File: engine/src/main/java/org/terasology/engine/config/SystemConfig.java [hunk 1]
```diff
@@ -81,7 +83,7 @@ public class SystemConfig extends AutoConfig {
 
     public final Setting<Locale> locale = setting(
             type(Locale.class),
-            defaultValue(Locale.getDefault(Category.DISPLAY)),
+            defaultValue(getAdjustedLocale()),
```
Comment (jdrueckert) [inline engine/src/main/java/org/terasology/engine/config/SystemConfig.java:89]: Would it make sense to only do this if the locale cannot be found, e.g. because it's a weird one?
This would allow to keep regional differences like `en_US` vs `en_GB` or `en_NZ` while fixing the macos issue.

**Review by jdrueckert — APPROVED** [review]

**Comment by soloturn** [comment]
very cool @rzats, thank you!
