### PR TITLE
Fix advanced chunk monitoring system

### LINKED ISSUE #3010: Advanced chunk monitor prevents game from closing cleanly
### What you were trying to do

Run and close the game cleanly with `monitoringEnabled` set to true (for example to test #3006)

### What actually happened

Game windows (there are two with the monitor visible) closed, but the game didn't exit. Some thread triggered by the monitor isn't exiting on game exit

### How to reproduce

* Toggle `"monitoringEnabled": false,` to `true` in `config.cfg` (run the game once to get one)
* Run the game
* Close the game
* Protip: Trigger a thread dump in IntelliJ to inspect threads that are still alive after exiting (little camera looking icon near the bottom left, in the run window)

### PR DESCRIPTION
**Pull request by llvieira**
### Contains

Fixes #3010. The goal here is to fix the problem of preventing the game from close cleanly. After dive into the code I realize that the **Thread** created by `ExecutorService` in `ThreadMonitorPanel`, `PerformanceMonitorPanel` and `ChunkMonitorDisplay` keeps running after the game closes. Therefore, I changed a little the way thread monitors work. Also the whole monitor code were cleaned up.

To fix the problem I created a variable called `stopThread` for each of the three monitors. If `stopThread` is `true` then the monitor thread leaves the loop and the executor service is shutdown, which will allow the game to close gracefully.

### How to test

- Toggle `"monitoringEnabled": false`, to `true` in `config.cfg` (run the game once to get one).
- Run the game.
- Close the game.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

File: engine/src/main/java/org/terasology/monitoring/gui/ChunkMonitorDisplay.java [hunk 1]
```diff
@@ -105,13 +104,18 @@ public ChunkMonitorDisplay(int refreshInterval, int chunkSize) {
         addMouseListener(ml);
         addMouseMotionListener(ml);
         addMouseWheelListener(ml);
+        this.followPlayer = true;
```
Comment (Cervator) [inline engine/src/main/java/org/terasology/monitoring/gui/ChunkMonitorDisplay.java]: With the removal of `setFollowPlayer` this var itself might be obsolete since there's no way to change it. Probably either keep the setter in expectation that it'll be added as a toggle in the UI sometime or just remove it entirely :-)

File: engine/src/main/java/org/terasology/monitoring/gui/ChunkMonitorDisplay.java [hunk 2]
```diff
@@ -62,18 +62,13 @@
...
 
-    public static final Color COLOR_HIGHLIGHT_TESSELLATION = Color.blue.brighter().brighter();
-
-    public static final Color COLOR_SELECTED_CHUNK = new Color(255, 102, 0);
-
-    public static final Color COLOR_DEAD = Color.lightGray;
-    public static final Color COLOR_INVALID = Color.red;
-
-    private static final Logger logger = LoggerFactory.getLogger(ChunkMonitorDisplay.class);
+    private static final Logger LOGGER = LoggerFactory.getLogger(ChunkMonitorDisplay.class);
```
Comment (Cervator) [inline engine/src/main/java/org/terasology/monitoring/gui/ChunkMonitorDisplay.java]: All caps logger or not is a tricky subject. See https://stackoverflow.com/questions/1417190/should-a-static-final-logger-be-declared-in-upper-case - generally we've kept it lower case so probably best to stay consistent that way, at least for now :-)

File: engine/src/main/java/org/terasology/monitoring/gui/ChunkMonitorDisplay.java [hunk 3]
```diff
@@ -694,12 +631,12 @@ private void renderSelectedChunk(Graphics2D g, int offsetx, int offsety, Vector3
         }
 
         private void renderBox(Graphics2D g, int offsetx, int offsety, Rectangle box) {
-            g.setColor(Color.white);
+            g.setColor(Color.WHITE);
```
Comment (Cervator) [inline engine/src/main/java/org/terasology/monitoring/gui/ChunkMonitorDisplay.java]: This case change on the other hand is definitely good 👍

File: engine/src/main/java/org/terasology/monitoring/gui/PerformanceMonitorPanel.java [hunk 4]
```diff
@@ -37,22 +47,27 @@
...
 @SuppressWarnings("serial")
 public class PerformanceMonitorPanel extends JPanel {
-    private static final Logger logger = LoggerFactory.getLogger(PerformanceMonitorPanel.class);
-
-    private final HeaderPanel header;
-    private final JList list;
+    private static final Logger LOGGER = LoggerFactory.getLogger(PerformanceMonitorPanel.class);
 
+    /**
+     * If true, the active monitoring thread in executor service should stop.
```
Comment (Cervator) [inline engine/src/main/java/org/terasology/monitoring/gui/PerformanceMonitorPanel.java]: Another could-be one-liner

File: engine/src/main/java/org/terasology/monitoring/gui/AdvancedMonitor.java [hunk 5]
```diff
@@ -36,21 +35,36 @@ public AdvancedMonitor(String title, int x, int y, int width, int height) {
...
         tabs.add("Threads", threadMonitor);
         tabs.add("Chunks", chunkMonitor);
-        tabs.add("Performance", perfMonitor);
+        tabs.add("Performance", performanceMonitor);
 
         add(tabs, BorderLayout.CENTER);
     }
+
+    /**
+     * This method goes through three steps:
```
[the remark this answers is not in the document]
Comment (llvieira) [reply engine/src/main/java/org/terasology/monitoring/gui/AdvancedMonitor.java]: Got it. Fixed! :-)

File: engine/src/main/java/org/terasology/monitoring/gui/ChunkMonitorDisplay.java [hunk 6]
```diff
@@ -89,13 +84,17 @@
...
 
     private Vector3i selectedChunk;
 
-    private final BlockingQueue<Request> queue = new LinkedBlockingQueue<>();
+    private final BlockingQueue<Request> queue;
     private final transient ExecutorService executor;
-    private final transient Runnable renderTask;
+
+    /**
+     * If true, the active monitoring thread in executor service should stop.
```
[the remark this answers is not in the document]
Comment (llvieira) [reply engine/src/main/java/org/terasology/monitoring/gui/ChunkMonitorDisplay.java]: Done!

File: engine/src/main/java/org/terasology/monitoring/gui/ChunkMonitorDisplay.java (hunk 2 above)
Comment (llvieira) [reply engine/src/main/java/org/terasology/monitoring/gui/ChunkMonitorDisplay.java]: Indeed, according to _Java Code Style_ is should be lower-case. I changed it after CheckStyle scan, however CheckStyle cannot check if this object reference is never followed by a ".".

File: engine/src/main/java/org/terasology/monitoring/gui/ChunkMonitorDisplay.java (hunk 3 above)
Comment (llvieira) [reply engine/src/main/java/org/terasology/monitoring/gui/ChunkMonitorDisplay.java]: Thanks! :smiley:

File: engine/src/main/java/org/terasology/monitoring/gui/PerformanceMonitorPanel.java (hunk 4 above)
Comment (llvieira) [reply engine/src/main/java/org/terasology/monitoring/gui/PerformanceMonitorPanel.java]: Fixed!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

File: engine/src/main/java/org/terasology/monitoring/gui/ChunkMonitorDisplay.java (hunk 1 above)
Comment (llvieira) [reply engine/src/main/java/org/terasology/monitoring/gui/ChunkMonitorDisplay.java]: I decided to keep the setter, so we can open an issue to add that new UI functionality.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
All good, thanks! :-)
