### PR TITLE
fix(PathManager): avoid calling Files method on paths that may not exist yet

### LINKED ISSUE #4587: NoSuchFileException from PathManager.defaultModPaths
as seen in [Pathfinding tests on CI](http://jenkins.terasology.io/teraorg/job/Terasology/job/Modules/view/Unhealthy/job/P/job/Pathfinding/job/develop/lastCompletedBuild/testReport/org.terasology.pathfinding/HAStarLoSTest/flat__/):

```
java.nio.file.NoSuchFileException: /home/jenkins/.local/share/terasology
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) […]
	at sun.nio.fs.UnixFileSystemProvider.isSameFile(UnixFileSystemProvider.java:332)
	at java.nio.file.Files.isSameFile(Files.java:1504)
	at org.terasology.engine.core.paths.PathManager.defaultModPaths(PathManager.java:344)
	at org.terasology.engine.core.paths.PathManager.updateDirs(PathManager.java:311)
	at org.terasology.engine.core.paths.PathManager.useDefaultHomePath(PathManager.java:185)
	at org.terasology.pathfinding.HAStarLoSTest.before(HAStarLoSTest.java:37)
```

I must have introduced this in https://github.com/MovingBlocks/Terasology/pull/4556

### PR DESCRIPTION
**Pull request by keturn**
Fixes #4587 

I've reached the point in the day when I'm wondering

_is it `==` or `.equals()`?_

_how does Java work?_

_what am I going to do about dinner?_

### CODE REVIEW

File: engine/src/main/java/org/terasology/engine/core/paths/PathManager.java [hunk 1]
```diff
@@ -341,7 +341,7 @@ private void updateDirs() throws IOException {
         Path homeModPath = homePath.resolve(MODULE_DIR);
         Path modCachePath = homePath.resolve(MODULE_CACHE_DIR);
 
-        if (Files.isSameFile(homePath, installPath)) {
+        if (homePath == installPath) {
```
Comment (pollend) [inline engine/src/main/java/org/terasology/engine/core/paths/PathManager.java:344]: oh man...

**Review by pollend — APPROVED** [review]
