### PR TITLE
Compile against Java 17

### LINKED ISSUE #3976: Java 17 compatibility
_Edit: For those troubleshooting Java issues see also [this page](https://github.com/MovingBlocks/Terasology/wiki/Troubleshooting-Developer#java)_

Java 17 is the latest Long-Term Service release. Distributions are available from [Adoptium](https://adoptium.net/releases.html?variant=openjdk17) as of September 22, 2021.

It is the first LTS release to have [jpackage](https://docs.oracle.com/en/java/javase/14/jpackage/packaging-overview.html), the low-latency garbage collectors [ZGC](https://openjdk.java.net/jeps/377) and [Shenandoah](https://openjdk.java.net/jeps/379), and maybe if we're lucky, the new [foreign memory access API](https://openjdk.java.net/jeps/370). Just to name a few things of potential interest to game development in addition to the other language niceties.

I thought it'd be good to have a tracking issue as a place to attract notes about problems that come up when people try using java 14, java 15, java 16, or java 17.

### What you were trying to do

play (or develop) Terasology on the latest release of the JDK version ▁▁

### What actually happened

As soon as I ▁(_verb_)▁ the ▁(_noun_)▁, Gooey Jr turned in to an ▁(_animal_)▁ and said: ▁▁▁▁▁▁▁▁

### How to reproduce

* Step 1
* Step 2
* Step 3

### PR DESCRIPTION
**Pull request by BenjaminAmos**
### Contains
This pull request updates the game to build and run under Java 17. It increases the minimum required JDK version to 17.

Both JUnit and Mockito in `engine-tests` have been updated since the older versions would not run under Java 17.

### How to test
- The game should start-up without crashing.
- You should also be able to create a new world and start playing in it.
- You should be able to place and destroy blocks within the world.
- The game should play as before.

### Notes
- This depends on MovingBlocks/Logistics#9 and MovingBlocks/JenkinsAgentPrecachedJava#4 in a complicated fashion. Both of those pull requests technically depend on this pull request, creating a cyclic dependency. Manually pushing the initial builder image may be needed to resolve this.

Closes #3976

### CODE REVIEW

**Review by soloturn — APPROVED** [review]

File: engine-tests/src/test/java/org/terasology/engine/entitySystem/PojoEventSystemTests.java [hunk 1]
```diff
@@ -191,7 +191,7 @@ public void testEventReceiverRegistration() {
         assertEquals(1, receiver.eventList.size());
     }
 
-    private static class TestEvent extends AbstractConsumableEvent {
+    public static class TestEvent extends AbstractConsumableEvent {
```
Comment (jdrueckert) [inline engine-tests/src/test/java/org/terasology/engine/entitySystem/PojoEventSystemTests.java:194]: why does this have to be `public` now?

File: engine-tests/src/test/java/org/terasology/engine/recording/EventSystemReplayImplTest.java [hunk 2]
```diff
@@ -169,7 +169,7 @@ public static class Received {
         }
     }
 
-    private static class TestEvent extends AbstractConsumableEvent {
+    public static class TestEvent extends AbstractConsumableEvent {
```
Comment (jdrueckert) [inline engine-tests/src/test/java/org/terasology/engine/recording/EventSystemReplayImplTest.java:172]: see above

**Review by jdrueckert — APPROVED** [review]
Tests out fine :+1: 

We should also adjust the JDK recommendation in the contributor quickstart guide.
But this is not blocking and can be done in a follow-up PR if desired.

File: engine-tests/src/test/java/org/terasology/engine/entitySystem/PojoEventSystemTests.java (hunk 1 above)
Comment (BenjaminAmos) [reply engine-tests/src/test/java/org/terasology/engine/entitySystem/PojoEventSystemTests.java:194]: Java 17 is a lot stricter about accessing private members via reflection. We were able to get away with this before under Java 11 because it only produced a warning.

```stacktrace
java.lang.IllegalAccessError: failed to access class org.terasology.engine.entitySystem.PojoEventSystemTests$TestEvent from class org.terasology.engine.entitySystem.PojoEventSystemTests$TestEventHandlerMethodAccess (org.terasology.engine.entitySystem.PojoEventSystemTests$TestEvent is in unnamed module of loader 'app'; org.terasology.engine.entitySystem.PojoEventSystemTests$TestEventHandlerMethodAccess is in unnamed module of loader com.esotericsoftware.reflectasm.AccessClassLoader @319988b0)
	at org.terasology.engine.entitySystem.PojoEventSystemTests$TestEventHandlerMethodAccess.invoke(Unknown Source)
	at org.terasology.engine.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:399)
	at org.terasology.engine.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:274)
	at org.terasology.engine.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:253)
	at org.terasology.engine.entitySystem.PojoEventSystemTests.testChildEvent(PojoEventSystemTests.java:164)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:728)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.SameThreadTimeoutInvocation.proceed(SameThreadTimeoutInvocation.java:45)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:218)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:214)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:139)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:119)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:94)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:89)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

Comment (jdrueckert) [reply engine-tests/src/test/java/org/terasology/engine/entitySystem/PojoEventSystemTests.java:194]: Sounds good 👍

**Comment by jdrueckert** [comment]
Merge strategy:
1. merge https://github.com/MovingBlocks/JenkinsAgentPrecachedJava/pull/5
1. merge https://github.com/MovingBlocks/JenkinsAgentPrecachedJava/pull/6
1. merge https://github.com/MovingBlocks/Logistics/pull/9
1. merge https://github.com/MovingBlocks/Terasology/pull/5162

**Comment by jdrueckert** [comment]
Added a reference to #3976 to the PR description
