### PR TITLE
Fix getText() function in UIText

### LINKED ISSUE #3688: Terrible things happen when starting a _second_ game without a game restart
### What you were trying to do

Test unrelated things! Which sometimes involve jumping into more than one world.

### What actually happened

Inconsistently would get warped worlds with messed up data, from broken chunks to entirely messed up block data (hills of torches, pure water world, etc)

### How to reproduce

This is the minimal use case I could consistently reproduce real quick

* Step 0: (Unsure if needed: start from a clean game, no saves or config)
* Step 1: Start the game from source, create a new game, pick Core, quick start
* Step 2: Verify all looks well, exit back to the main menu
* Step 3: Create a new game, pick Core, quick start - bad things happen

Similar issues have happened in the past (malformed block ids through some scenario), but I thought they were all long gone. Game state handling between multiple games in one game launch has remained a fragile area, however. Chances are something isn't being reset properly when leaving the first game world.

### PR DESCRIPTION
**Pull request by darshan3**
### Contains

Fixes #3688

### How to test

Start from a clean game with no save games. Try reproducing #3688, in both the ways stated over there. The new game should load properly now.

### CODE REVIEW

**Comment by darshan3** [comment]
The getText() function was incorrectly adding a '\n' character, which leads to parsing error `GameProvider.getNextGameName()`. Hence, when it incorrectly returns the game name as 'Game 1' even if saved games are present with the same name. This leads to further errors in loading and saving the game in the same directory.

**Comment by darshan3** [comment]
I would also request @jellysnake or @eviltak  to have a look once since I don't know how multiline text works and haven't tested it out for the changes in this pr.

File: engine/src/main/java/org/terasology/rendering/nui/widgets/UIText.java [hunk 1]
```diff
@@ -677,15 +677,15 @@ public void bindText(Binding<String> binding) {
...
-        if(linesOfText.length > 0) {
-            arrayText = String.join("\n", linesOfText);
-        }
-
-        if(text.get() != "") {
-            return text.get() + "\n" + arrayText;
+        if (linesOfText.length > 0) {
+            String arrayText = String.join("\n", linesOfText);
+            if (text.get().equals("")) {
+                return text.get() + "\n" + arrayText;
```
Comment (skaldarnar) [inline engine/src/main/java/org/terasology/rendering/nui/widgets/UIText.java]: In this case `text.get()` is the empty string `""` - why are we prepending a newline here? Should it rather be:

```java
 if (text.get().equals("")) {
    return arrayText;
} else {
    return text.get() + "\n" + arrayText;
}
```

Comment (darshan3) [reply engine/src/main/java/org/terasology/rendering/nui/widgets/UIText.java]: My mistake, it should be `!text.get().equals("")`. I will fix it.

Comment (darshan3) [reply engine/src/main/java/org/terasology/rendering/nui/widgets/UIText.java]: Should I just return `arrayText` instead of `text.get() + arrayText`? There was a discussion in original pr #3678 regarding this but resolved eventually.

**Comment by Cervator** [comment]
Tested out a fair bit - merging! :-)

Since this fixes a blocker I figure merge sooner, ask more questions later if needed. Existing saves may still cause problems even after the fix (since I guess a bad name might persist that way) but in a clean workspace I didn't see any issues colliding with new saves.

**Comment by eviltak** [comment]
Reverted with #3678.
