### PR TITLE
fix: fix game screen goes black bug

### LINKED ISSUE #4929: Game screen goes Black
### What you were trying to do
So I was switching the Window to read the docs/playing.md(basically I paused the game, minimized the window and opened a new window like chrome, etc).
### What actually happened
Once I came back to the game and resumed playing the whole screen went black although I could switch between my tools and blocks. I remember standing on a high tower of blocks, as the screen was black I quit to the main menu and reloaded the game and I was there standing on the same tower of blocks(this means I continued the game where I left although the video wasn't there). I also tried to do this again and this time when the screen went black I tried sprinting and I fell down to death and still, the screen was black...
### How to reproduce

* Open and play the game and then pause the game.
* Now switch to another window by minimizing the game window. You will have to minimize the game window and then switch to the other window, if you directly switch to the other windows(like chrome, etc) using the taskbar, you won't encounter the problem.
* Now come back to the game window and resume the game. You will just see a black screen.
* Alternatively you can minimize the game window and reopen the game window and you will encounter the same problem.

### Log details and game version
Latest develop branch as of Oct 23 rd.
### Computer details
Asus Tuf F-15

### PR DESCRIPTION
**Pull request by sid2002CN**
### Contains

Fixes #4929

### How to test

Play the game and then pause the game.
Minimize the game window.
Bring back the game window and resume the game.

### CODE REVIEW

File: engine/src/main/java/org/terasology/engine/rendering/opengl/FBO.java [hunk 1]
```diff
@@ -728,6 +728,9 @@ public int height() {
          * @param height An integer representing the new height.
          */
         public void setDimensions(int width, int height) {
+            if(width == 0 && height ==0){
```
Comment (Cervator) [inline engine/src/main/java/org/terasology/engine/rendering/opengl/FBO.java:731]: Minor code quality fixes here, explained by the robot :-)

Should this just check for an _or_ rather than _and_ ? In the case we're dealing with _both_ dimensions are zero. But it seems like _either_ being zero would be a case where you'd disregard the instruction and return early.

Additionally, maybe it would be good if we did a `logger.warn(....)` to highlight that the set was called with invalid dimensions?

File: engine/src/main/java/org/terasology/engine/rendering/opengl/FBO.java [hunk 2]
```diff
@@ -737,6 +740,9 @@ public void setDimensions(int width, int height) {
          * @param other A Dimension to use the width and height from.
          */
         public void setDimensions(Dimensions other) {
+            if(width == 0 && height ==0){
```
Comment (Cervator) [inline engine/src/main/java/org/terasology/engine/rendering/opengl/FBO.java:743]: In addition to my other review content in this case shouldn't we be checking `other.width` and same for height?

**Review by Cervator — CHANGES_REQUESTED** [review]
Can confirm this fixes the issue! Mostly, anyway :-)

I replicated the issue before merging, and confirmed the same steps after would no longer encounter the problem - _after_ I dismissed the in-world menu and moved ever so slightly to cause the dimensions to refresh and redraw the screen. However, right as you bring up the game from being minimized the background is still black behind the menu.

So this could _probably_ be fixed more thoroughly, but that's a triviality and this fixes the important bits! Maybe we should leave the issue open as a longer priority to see about finding an "earlier" fix that doesn't cause the blackness to occur in the first place. But I have no idea where to find that, and it isn't very important after this fix :-)

Nice work @sid2002CN ! I have left a couple review comments with trivial adjustments needed. A couple things you could do in the future:

* Make sure you look for warnings in your IDE about style warnings and such, if you're introducing new ones (just missing some spaces in this case). You can run a Checkstyle plugin within IntelliJ for more details
* Consider learning about and using "topic branches" rather than your `develop` branch, for :reasons: that a quick Google search will highlight along with how to do it - don't worry about that for this PR though, just made the tweaks in a second commit in your `develop` branch and we'll merge them!

Thanks!

File: engine/src/main/java/org/terasology/engine/rendering/opengl/FBO.java [hunk 3]
```diff
@@ -728,6 +728,9 @@ public int height() {
          * @param height An integer representing the new height.
          */
         public void setDimensions(int width, int height) {
```
Comment (pollend) [inline engine/src/main/java/org/terasology/engine/rendering/opengl/FBO.java:730]: that's just obscuring the problem by having the method silently fail.

**Review by pollend — CHANGES_REQUESTED** [review]

**Comment by sid2002CN** [comment]
@Cervator Thanks for your suggestions! This is my first attempt to contribute to an open-source project. I am happy that I have done this in the right way(almost).
As for >finding an "earlier" fix that doesn't cause the blackness to occur in the first place, I kind of get lost on trying to find where to look for. Does anyone know which class actually set the width and height of the FBO?

File: engine/src/main/java/org/terasology/engine/rendering/opengl/FBO.java (hunk 3 above)
Comment (pollend) [reply engine/src/main/java/org/terasology/engine/rendering/opengl/FBO.java:730]: the precondition should hit and give you a backtrace and give you information where this is coming from. I don't know off the top of my head why its getting set to 0,0

**Comment by sid2002CN** [comment]
Thanks to @Cervator and @pollend's suggestion I found out what actually goes wrong. The width and height of displayDevice are not updated properly as the screen goes back to normal after being minimized. The new solution updates the displayDevice before updating the full-scale if width or height is 0.

**Comment by Cervator** [comment]
@sid2002CN very nice detective work! However, oddly enough, I still get the black screen after restoring the window 🤔 Not sure if that is a problem on my end, it would be good with another opinion or two.

Not sure what's happening there, I tried a few different ways to lose focus / minimize and they all result in the same thing. Black behind the pause menu until I dismiss the menu and do anything to trigger a refresh of the world view.

Your fix sounds reasonable, but maybe there are more places to capture? One interesting thing I noticed is that with the game minimized the Windows 10 task bar preview _does_ show the small version of the game window with valid background behind the pause menu. It just doesn't work as I restore the window size - maybe the act of restoring the window is still capturing and storing a 0,0 somewhere?

I don't really know what `displayDevice.update();` does other than what I can assume. Even before testing I wondered if it might still make sense to have the precondition checks _after_ the attempt to run the update, in case there are cases we don't catch.

**Comment by sid2002CN** [comment]
@Cervator Thanks for your feedback. I finally got what actually goes wrong. The updateViewport capturing and storing 0,0 during the screen is minimized. The simple solution will be to block the change when the screen is minimized. After spending some time learning how to use GLFW, I come up with this solution.

**Comment by Cervator** [comment]
Amazingly well done! I love that you're willing to go this deep into research land to find the proper solution :-)

And I can confirm that it works this time! No more blackness behind the pause menu!

I did however still find an edge case that provokes the original crash though, so there's one more bit of detective work for you 😁 

* Run game, enter world in CoreSampleGameplay
* _Without_ opening the pause menu screen hit the Windows button
* Click a different window to move the focus
* Without otherwise activating the game window click the minimize button on its menu bar
* OG crash!

I dunno if that is capturable similarly or justifies putting the zero check back, now perhaps without the blackness (since it did prevent the crash itself - maybe now it would both not crash _and_ bypass the blackness?). I might suggest having the check there (with preconditions maybe, if that can prevent the crash gentle and be informative) still, even if we resolve the issue. A simple comment explaining briefly why we do the thing would also be helpful

So close now! Thank you very much for the effort here :-)

**Comment by sid2002CN** [comment]
@Cervator Never thought of testing it in that way. 😁
It is now fixed with the new commit. It turns out that the game still tries to render the screen after we minimize the game. 
I am not sure how to write in-class comments about this properly. Is there a formal format or I can add comments which simply describe what I have changed?

**Comment by Cervator** [comment]
Great to hear about the final fix 👍 

Comment would just be a one liner `// ...` for probably the first change since it includes a property change event and some logic - simply suggest a reason for _why_ we might do / need that., so that it is clear to a reader.

The other change I think documents itself by simply using the well-named boolean. You could read that code without comments as "Ah so if the thing isn't minimized then do this other thing, seems sensible"

**Comment by sid2002CN** [comment]
@Cervator Just finished the comment change.

**Comment by Cervator** [comment]
Well done - I can't find a way to crash it or see black in the background now. And the comment is on point 👍 

Apologies for taking a little while to get back to this, but the weekend ended 😁 

Approving and merging! Woot!

**Review by Cervator — APPROVED** [review]
