### PR TITLE
fixed singlePlayer and multiPlayer screen disappearance after enabling Animated Menus option

### LINKED ISSUE #2762: Animated menus can cause issues returning from some screens
### What you were trying to do
Close credits and see menu
### What actually happened
I see only background
### How to reproduce
* Open Terasology dev 1916
* enable "animated menus" in options
* ~~click "credits"->"back"~~ (fixed)
  * or "singleplayer"->"back"->"singleplayer"
  * or "singleplayer"->"back->"multiplayer" (any other combination should work)
  * or "multiplayer"->"back"->"singleplayer"
  * in short:  "singleplayer"/"multiplayer"->"back"->anything except single or multi any number of times->single/multi
* See only background image instead of menu

### Log details and game version
 Terasology dev 1916  
### Computer details
 OS: Ubuntu 16.10 yakkety, kernel: x86_64 Linux 4.8.0-34-generic
 dual-screen
 CPU: Intel Core i5-5200U CPU @ 2.7GHz
 Java version "1.8.0_121"
 GPU: GeForce 920M
 RAM: 7886MiB

### PR DESCRIPTION
**Pull request by 0shine0**
Fixes disappearance of buttons that should come after clicking Singleplayer and Host Game buttons in main menu.
#2762 partially fixed already in pr 2772 and completely fixed after this

### Contains

Fixes #2762 

### How to test

1. Enable animated menus in settings > video
2. go back to main screen
3. click Singleplayer or Host Game button
4. click Back
5. click any among the Singleplayer or Host Game button

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
@Halamix2 @Malanius could either of you try this out please? :-) Seems simple enough, but need to watch out for unexpected consequences.

@GooeyHub: ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Halamix2** [comment]
It's working, I didn't have any problems now  
Hooray Halamix2 reported success with no unexpected consequences :D
(tested with animated menus turned on and off)

**Comment by Malanius** [comment]
I can also confirm it works as expected now. I haven't found any side effects.
Good work, @0shine0 !

**Comment by Cervator** [comment]
Thanks for confirming! And thanks for the PR @0shine0 - added you to credits, got you a contributor badge in the forum, etc :-)

File: engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectGameScreen.java [hunk 1]
```diff
@@ -122,6 +122,7 @@ public boolean isLowerLayerVisible() {
 
     @Override
     public void onOpened() {
+    	super.onOpened();
```
Comment (Cervator) [inline engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectGameScreen.java]: Eeeeevil tab character! We follow the space side of the Force :D

You should be able to configure your editor to prefer 4 spaces instead of a tab char :-)

(fixing as part of merge so no worries here)
