### PR TITLE
fix: make entity dump filename windows compatible

### LINKED ISSUE #5144: Entity Dump broken on Windows
### General Info

Terasology Launcher Version: 4.8.0
Terasology Version: 5.3.0
Operating System: Windows 11
Onboard / Dedicated Graphics: Dedicated
Java Version: Launcher-bundled

### What you were trying to do

Dump entities from the in-game console of a Terasology world, running on Windows.

### What actually happened

`An error occurred while executing command 'dumpEntities': Illegal char <:> at index 13: 2023-09-27T20:52:11.811415100Z-entityDump.json`

### How to reproduce

1. Select Terasology version '5.3.0'
1. Start Terasology
1. Select gameplay 'CoreGameplay' (any)
1. Start game
1. Open in-game console (F1)
1. Execute `dumpEntities`
1. See error

### Log details

```
22:52:11.815 [main] ERROR o.t.engine.logic.console.ConsoleImpl - An error occurred while executing a command
org.terasology.engine.logic.console.commandSystem.exceptions.CommandExecutionException: java.nio.file.InvalidPathException: Illegal char <:> at index 13: 2023-09-27T20:52:11.811415100Z-entityDump.json
	at org.terasology.engine.logic.console.commandSystem.AbstractCommand.execute(AbstractCommand.java:229)
	at org.terasology.engine.logic.console.ConsoleImpl.execute(ConsoleImpl.java:251)
[...]
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 13: 2023-09-27T20:52:11.811415100Z-entityDump.json
	at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at java.base/java.nio.file.Path.resolve(Unknown Source)
	at org.terasology.engine.logic.console.commands.CoreCommands.dumpEntities(CoreCommands.java:482)
```

### Workaround

Use Linux 🤪

### PR DESCRIPTION
**Pull request by jdrueckert**
### Contains

- windows doesn't allow colons (':') in filenames
- so far the filename included the timestamp in format YYYY-MM-DDTHH:MM:SS.MSZ, e.g. 2023-09-28T17:01:31.685172Z-entityDump.json
- now colons will be replaced by dashes ('-')

### How to test

1. Start any Terasology world on Windows with this branch checked out
2. Open the in-game console (F1) and execute `dumpEntities`
3. Verify that Terasology does not crash and that an entity dump file without colons in its name is created

### Outstanding before merging

- [ ] confirming the fix

Fixes #5144

### CODE REVIEW

File: engine/src/main/java/org/terasology/engine/logic/console/commands/CoreCommands.java [hunk 1]
```diff
@@ -479,7 +479,7 @@ public String dumpEntities(@CommandParam(value = "componentNames", required = fa
         PrefabSerializer prefabSerializer =
                 new PrefabSerializer(engineEntityManager.getComponentLibrary(), engineEntityManager.getTypeSerializerLibrary());
         WorldDumper worldDumper = new WorldDumper(engineEntityManager, prefabSerializer);
-        Path outFile = PathManager.getInstance().getHomePath().resolve(Instant.now() + "-entityDump.json");
+        Path outFile = PathManager.getInstance().getHomePath().resolve(Instant.now().toString().replaceAll(":", "-") + "-entityDump.json");
```
Comment (soloturn) [inline engine/src/main/java/org/terasology/engine/logic/console/commands/CoreCommands.java:482]: would it not be cleaner to use the iso-8601 basic format in general, and not the extended format? see:
https://stackoverflow.com/questions/27725408/alternative-to-colon-in-a-time-format

**Review by BenjaminAmos — APPROVED** [review]
I can confirm that using the `dumpEntities` commmand does not crash on Windows when testing this pull request.

Windows sometimes makes use of colons in file names for an obscure NTFS feature called [file streams](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-fscc/c54dec26-1551-4d3a-a0ea-4fa40f848eb3). Using that feature usually isn't what you'd want, since it makes the data invisible to most normal programs. There are other special filenames that you should't use but those are just obscure edge-cases that we're unlikely to run into.
